graphs.c
PI
Referenced by calc_arc.
COLOR1
Referenced by month_graph6.
COLOR2
COLOR3
COLOR4
COLOR5
COLOR6
CX
Referenced by calc_arc, pie_chart.
CY
Referenced by calc_arc, pie_chart.
XRAD
Referenced by calc_arc, pie_chart.
YRAD
Referenced by calc_arc, pie_chart.
YSIZE
void init_graph(char *, int, int)
References black, blue, cyan, dkgrey, green, grey, im, orange, red, white, yellow.
Referenced by day_graph3, month_graph6, pie_chart, year_graph6x.
struct pie_data * calc_arc(float, float)
References CX, CY, pie_data::mx, pie_data::my, PI, pie_data::x, XRAD, pie_data::y, YRAD.
Referenced by pie_chart.
int year_graph6x(char *fname, char *title, int fmonth, u_long data1[12], u_long data2[12], u_long data3[12], double data4[12], u_long data5[12], u_long data6[12])
References black, dkgrey, graph_lines, im, init_graph, s_month, white.
int month_graph6(char *fname, char *title, int month, int year, u_long data1[31], u_long data2[31], u_long data3[31], double data4[31], u_long data5[31], u_long data6[31])
References black, COLOR1, dkgrey, graph_lines, im, init_graph, jdate, julday, numchar, white.
Referenced by write_month_html.
int day_graph3(char *fname, char *title, u_long data1[24], u_long data2[24], u_long data3[24])
References black, dkgrey, graph_lines, im, init_graph, numchar.
Referenced by write_month_html.
int pie_chart(char *fname, char *title, u_long t_val, u_long data1[], char *legend[])
References black, buffer, calc_arc, CX, CY, im, init_graph, percent, pie_data::x, XRAD, pie_data::y, YRAD.
char* numchar[][]
Referenced by day_graph3, month_graph6.
gdImagePtr im
Referenced by day_graph3, init_graph, month_graph6, pie_chart, year_graph6x.
FILE* out
char maxvaltxt[32][32]
float percent
Referenced by pie_chart.
u_long julday
Referenced by month_graph6.
int black
Referenced by day_graph3, init_graph, month_graph6, pie_chart, year_graph6x.
int white
Referenced by init_graph, month_graph6, year_graph6x.
int grey
Referenced by init_graph.
int dkgrey
Referenced by day_graph3, init_graph, month_graph6, year_graph6x.
int red
Referenced by init_graph.
int blue
Referenced by init_graph.
int orange
Referenced by init_graph.
int green
Referenced by init_graph.
int cyan
Referenced by init_graph.
int yellow
Referenced by init_graph.