hashtab.c
CLK_TCK
HNODEPTR new_hnode(char *)
References blank_str, debug_mode, hnode::lasturl, MAXHOST, msg_big_one, hnode::string, hnode::tstamp, verbose, hnode::visit.
Referenced by put_hnode.
UNODEPTR new_unode(char *)
References unode::count, debug_mode, unode::flag, MAXURLH, msg_big_one, OBJ_REG, unode::string, verbose.
Referenced by put_unode.
RNODEPTR new_rnode(char *)
References rnode::count, debug_mode, rnode::flag, MAXREFH, msg_big_one, OBJ_REG, rnode::string, verbose.
Referenced by put_rnode.
ANODEPTR new_anode(char *)
References anode::count, debug_mode, anode::flag, MAXAGENT, msg_big_one, OBJ_REG, anode::string, verbose.
Referenced by put_anode.
SNODEPTR new_snode(char *)
References snode::count, debug_mode, MAXSRCHH, msg_big_one, snode::string, verbose.
Referenced by put_snode.
INODEPTR new_inode(char *)
References debug_mode, MAXIDENT, msg_big_one, inode::string, inode::tstamp, verbose, inode::visit.
Referenced by put_inode.
void update_entry(char *)
References unode::entry, unode::flag, hash, unode::next, OBJ_GRP, unode::string, um_htab.
Referenced by put_hnode.
void update_exit(char *)
References unode::exit, unode::flag, hash, unode::next, OBJ_GRP, unode::string, um_htab.
Referenced by month_update_exit, put_hnode.
u_long hash(char *)
Referenced by find_url, put_anode, put_hnode, put_inode, put_rnode, put_snode, put_unode, update_entry, update_exit.
void del_htabs()
References am_htab, del_alist, del_hlist, del_ilist, del_rlist, del_slist, del_ulist, im_htab, rm_htab, sd_htab, sm_htab, sr_htab, um_htab.
Referenced by clear_month.
int put_hnode(char *str, int type, u_long count, u_long file, double xfer, u_long *ctr, u_long visit, u_long tstamp, char *lasturl, HNODEPTR *htab)
References hnode::count, hnode::files, find_url, hnode::flag, hash, hidden_sites, hide_sites, isinlist, ispage, hnode::lasturl, log_rec, new_hnode, hnode::next, OBJ_GRP, OBJ_HIDE, sm_htab, hnode::string, hnode::tstamp, update_entry, update_exit, log_struct::url, hnode::visit, visit_timeout, hnode::xfer.
void del_hlist(HNODEPTR *htab)
References MAXHASH, hnode::next, hnode::string.
Referenced by del_htabs.
int put_unode(char *str, int type, u_long count, double xfer, u_long *ctr, u_long entry, u_long exit, UNODEPTR *htab)
References unode::count, unode::entry, unode::exit, unode::flag, hash, hidden_urls, isinlist, new_unode, unode::next, OBJ_GRP, OBJ_HIDE, unode::string, unode::xfer.
void del_ulist(UNODEPTR *htab)
References MAXHASH, unode::next, unode::string.
Referenced by del_htabs.
int put_rnode(char *str, int type, u_long count, u_long *ctr, RNODEPTR *htab)
References rnode::count, rnode::flag, hash, hidden_refs, isinlist, new_rnode, rnode::next, OBJ_GRP, OBJ_HIDE, rnode::string.
void del_rlist(RNODEPTR *htab)
References MAXHASH, rnode::next, rnode::string.
Referenced by del_htabs.
int put_anode(char *str, int type, u_long count, u_long *ctr, ANODEPTR *htab)
References anode::count, anode::flag, hash, hidden_agents, isinlist, new_anode, anode::next, OBJ_GRP, OBJ_HIDE, anode::string.
void del_alist(ANODEPTR *htab)
References MAXHASH, anode::next, anode::string.
Referenced by del_htabs.
int put_snode(char *str, u_long count, SNODEPTR *htab)
References snode::count, hash, new_snode, snode::next, snode::string.
Referenced by srch_string.
void del_slist(SNODEPTR *htab)
References MAXHASH, snode::next, snode::string.
Referenced by del_htabs.
int put_inode(char *str, int type, u_long count, u_long file, double xfer, u_long *ctr, u_long visit, u_long tstamp, INODEPTR *htab)
References inode::count, inode::files, inode::flag, hash, hidden_users, isinlist, ispage, log_rec, new_inode, inode::next, OBJ_GRP, OBJ_HIDE, inode::string, inode::tstamp, log_struct::url, inode::visit, visit_timeout, inode::xfer.
void del_ilist(INODEPTR *htab)
References MAXHASH, inode::next, inode::string.
Referenced by del_htabs.
char* find_url(char *str)
References blank_str, hash, unode::next, unode::string, um_htab.
Referenced by put_hnode.
void month_update_exit(u_long tstamp)
References hnode::flag, hnode::lasturl, OBJ_GRP, sm_htab, hnode::tstamp, update_exit, visit_timeout.
u_long tot_visit(HNODEPTR *list)
References hnode::flag, MAXHASH, hnode::next, OBJ_GRP, hnode::visit.
HNODEPTR sm_htab[MAXHASH][MAXHASH]
Referenced by del_htabs, load_site_array, month_update_exit, put_hnode, top_ctry_table.
HNODEPTR sd_htab[MAXHASH][MAXHASH]
Referenced by del_htabs.
UNODEPTR um_htab[MAXHASH][MAXHASH]
Referenced by del_htabs, find_url, load_url_array, update_entry, update_exit.
RNODEPTR rm_htab[MAXHASH][MAXHASH]
Referenced by del_htabs, load_ref_array.
ANODEPTR am_htab[MAXHASH][MAXHASH]
Referenced by del_htabs, load_agent_array.
SNODEPTR sr_htab[MAXHASH][MAXHASH]
Referenced by del_htabs, load_srch_array, srch_string.
INODEPTR im_htab[MAXHASH][MAXHASH]
Referenced by del_htabs, load_ident_array.