hashtab.h
OBJ_REG
Referenced by all_agents_page, all_refs_page, all_sites_page, all_urls_page, all_users_page, new_anode, new_rnode, new_unode, top_agents_table, top_entry_table, top_refs_table, top_sites_table, top_urls_table, top_users_table.
OBJ_HIDE
Referenced by put_anode, put_hnode, put_inode, put_rnode, put_unode, top_agents_table, top_entry_table, top_refs_table, top_sites_table, top_urls_table, top_users_table.
OBJ_GRP
Referenced by all_agents_page, all_refs_page, all_sites_page, all_urls_page, all_users_page, dump_all_agents, dump_all_refs, dump_all_sites, dump_all_urls, dump_all_users, month_update_exit, put_anode, put_hnode, put_inode, put_rnode, put_unode, top_agents_table, top_ctry_table, top_refs_table, top_sites_table, top_urls_table, top_users_table, tot_visit, update_entry, update_exit.
typedef struct hnode* HNODEPTR
typedef struct unode* UNODEPTR
typedef struct rnode* RNODEPTR
typedef struct anode* ANODEPTR
typedef struct snode* SNODEPTR
typedef struct inode* INODEPTR
int put_hnode(char *, int, u_long, u_long, double, u_long *, u_long, u_long, char *, HNODEPTR *)
References hnode::count, hnode::files, find_url, hnode::flag, hash, hidden_sites, hide_sites, isinlist, ispage, hnode::lasturl, log_rec, new_hnode, hnode::next, OBJ_GRP, OBJ_HIDE, sm_htab, hnode::string, hnode::tstamp, update_entry, update_exit, log_struct::url, hnode::visit, visit_timeout, hnode::xfer.
int put_unode(char *, int, u_long, double, u_long *, u_long, u_long, UNODEPTR *)
References unode::count, unode::entry, unode::exit, unode::flag, hash, hidden_urls, isinlist, new_unode, unode::next, OBJ_GRP, OBJ_HIDE, unode::string, unode::xfer.
int put_inode(char *, int, u_long, u_long, double, u_long *, u_long, u_long, INODEPTR *)
References inode::count, inode::files, inode::flag, hash, hidden_users, isinlist, ispage, log_rec, new_inode, inode::next, OBJ_GRP, OBJ_HIDE, inode::string, inode::tstamp, log_struct::url, inode::visit, visit_timeout, inode::xfer.
int put_rnode(char *, int, u_long, u_long *, RNODEPTR *)
References rnode::count, rnode::flag, hash, hidden_refs, isinlist, new_rnode, rnode::next, OBJ_GRP, OBJ_HIDE, rnode::string.
int put_anode(char *, int, u_long, u_long *, ANODEPTR *)
References anode::count, anode::flag, hash, hidden_agents, isinlist, new_anode, anode::next, OBJ_GRP, OBJ_HIDE, anode::string.
int put_snode(char *, u_long, SNODEPTR *)
References snode::count, hash, new_snode, snode::next, snode::string.
Referenced by srch_string.
void del_htabs()
References am_htab, del_alist, del_hlist, del_ilist, del_rlist, del_slist, del_ulist, im_htab, rm_htab, sd_htab, sm_htab, sr_htab, um_htab.
Referenced by clear_month.
void del_hlist(HNODEPTR *)
References MAXHASH, hnode::next, hnode::string.
Referenced by del_htabs.
void del_ulist(UNODEPTR *)
References MAXHASH, unode::next, unode::string.
Referenced by del_htabs.
void del_rlist(RNODEPTR *)
References MAXHASH, rnode::next, rnode::string.
Referenced by del_htabs.
void del_alist(ANODEPTR *)
References MAXHASH, anode::next, anode::string.
Referenced by del_htabs.
void del_slist(SNODEPTR *)
References MAXHASH, snode::next, snode::string.
Referenced by del_htabs.
void del_ilist(INODEPTR *)
References MAXHASH, inode::next, inode::string.
Referenced by del_htabs.
void month_update_exit(u_long)
References hnode::flag, hnode::lasturl, OBJ_GRP, sm_htab, hnode::tstamp, update_exit, visit_timeout.
u_long tot_visit(HNODEPTR *)
References hnode::flag, MAXHASH, hnode::next, OBJ_GRP, hnode::visit.
char* find_url(char *)
References blank_str, hash, unode::next, unode::string, um_htab.
Referenced by put_hnode.
HNODEPTR sm_htab[MAXHASH][MAXHASH]
Referenced by del_htabs, load_site_array, month_update_exit, put_hnode, top_ctry_table.
HNODEPTR sd_htab[MAXHASH][MAXHASH]
Referenced by del_htabs.
UNODEPTR um_htab[MAXHASH][MAXHASH]
Referenced by del_htabs, find_url, load_url_array, update_entry, update_exit.
RNODEPTR rm_htab[MAXHASH][MAXHASH]
Referenced by del_htabs, load_ref_array.
ANODEPTR am_htab[MAXHASH][MAXHASH]
Referenced by del_htabs, load_agent_array.
SNODEPTR sr_htab[MAXHASH][MAXHASH]
Referenced by del_htabs, load_srch_array, srch_string.
INODEPTR im_htab[MAXHASH][MAXHASH]
Referenced by del_htabs, load_ident_array.