linklist.c
CLK_TCK
NLISTPTR new_nlist(char *)
References msg_big_one, nlist::next, nlist::string, verbose.
Referenced by add_nlist.
void del_nlist(NLISTPTR *)
References nlist::next.
GLISTPTR new_glist(char *, char *)
References msg_big_one, glist::name, glist::next, glist::string, verbose.
Referenced by add_glist.
void del_glist(GLISTPTR *)
References glist::next.
int isinstr(char *, char *)
Referenced by isinglist, isinlist.
int add_nlist(char *str, NLISTPTR *list)
References new_nlist, nlist::next.
Referenced by main.
int add_glist(char *str, GLISTPTR *list)
References new_glist, glist::next.
char* isinlist(NLISTPTR list, char *str)
References isinstr, nlist::next, nlist::string.
Referenced by ispage, main, put_anode, put_hnode, put_inode, put_rnode, put_unode.
char* isinglist(GLISTPTR list, char *str)
References isinstr, glist::name, glist::next, glist::string.
Referenced by srch_string.
GLISTPTR group_sites
GLISTPTR group_urls
GLISTPTR group_refs
GLISTPTR group_agents
GLISTPTR group_users
NLISTPTR hidden_sites
Referenced by main, put_hnode.
NLISTPTR hidden_urls
Referenced by main, put_unode.
NLISTPTR hidden_refs
Referenced by main, put_rnode.
NLISTPTR hidden_agents
Referenced by main, put_anode.
NLISTPTR hidden_users
Referenced by put_inode.
NLISTPTR ignored_sites
NLISTPTR ignored_urls
NLISTPTR ignored_refs
NLISTPTR ignored_agents
NLISTPTR ignored_users
NLISTPTR include_sites
NLISTPTR include_urls
NLISTPTR include_refs
NLISTPTR include_agents
NLISTPTR include_users
NLISTPTR index_alias
Referenced by main.
NLISTPTR html_pre
Referenced by write_html_head.
NLISTPTR html_head
Referenced by write_html_head.
NLISTPTR html_body
Referenced by write_html_head.
NLISTPTR html_post
Referenced by write_html_head.
NLISTPTR html_tail
Referenced by write_html_tail.
NLISTPTR html_end
Referenced by write_html_tail.
NLISTPTR page_type
Referenced by ispage, main.
GLISTPTR search_list
Referenced by srch_string.