linklist.h
typedef struct nlist* NLISTPTR
typedef struct glist* GLISTPTR
char* isinlist(NLISTPTR, char *)
References isinstr, nlist::next, nlist::string.
Referenced by ispage, main, put_anode, put_hnode, put_inode, put_rnode, put_unode.
char* isinglist(GLISTPTR, char *)
References isinstr, glist::name, glist::next, glist::string.
Referenced by srch_string.
int add_nlist(char *, NLISTPTR *)
References new_nlist, nlist::next.
Referenced by main.
int add_glist(char *, GLISTPTR *)
References new_glist, glist::next.
GLISTPTR group_sites
GLISTPTR group_urls
GLISTPTR group_refs
GLISTPTR group_agents
GLISTPTR group_users
NLISTPTR hidden_sites
Referenced by main, put_hnode.
NLISTPTR hidden_urls
Referenced by main, put_unode.
NLISTPTR hidden_refs
Referenced by main, put_rnode.
NLISTPTR hidden_agents
Referenced by main, put_anode.
NLISTPTR hidden_users
Referenced by put_inode.
NLISTPTR ignored_sites
NLISTPTR ignored_urls
NLISTPTR ignored_refs
NLISTPTR ignored_agents
NLISTPTR ignored_users
NLISTPTR include_sites
NLISTPTR include_urls
NLISTPTR include_refs
NLISTPTR include_agents
NLISTPTR include_users
NLISTPTR index_alias
Referenced by main.
NLISTPTR html_pre
Referenced by write_html_head.
NLISTPTR html_head
Referenced by write_html_head.
NLISTPTR html_body
Referenced by write_html_head.
NLISTPTR html_post
Referenced by write_html_head.
NLISTPTR html_tail
Referenced by write_html_tail.
NLISTPTR html_end
Referenced by write_html_tail.
NLISTPTR page_type
Referenced by ispage, main.
GLISTPTR search_list
Referenced by srch_string.