output.c
CLK_TCK
WHITE
BLACK
Referenced by write_html_head.
RED
Referenced by daily_total_table, hourly_total_table, top_sites_table, top_urls_table, top_users_table, write_html_head.
ORANGE
Referenced by daily_total_table.
LTBLUE
Referenced by daily_total_table, hourly_total_table, top_sites_table, top_users_table.
BLUE
Referenced by write_html_head.
GREEN
DKGREEN
Referenced by daily_total_table, hourly_total_table, top_agents_table, top_entry_table, top_refs_table, top_search_table, top_sites_table, top_urls_table, top_users_table.
GREY
Referenced by daily_total_table, hourly_total_table, top_agents_table, top_entry_table, top_refs_table, top_search_table, top_sites_table, top_urls_table, top_users_table.
LTGREY
Referenced by write_html_head.
YELLOW
Referenced by daily_total_table, top_entry_table, top_sites_table, top_users_table.
PURPLE
CYAN
Referenced by daily_total_table, hourly_total_table, top_agents_table, top_entry_table, top_refs_table, top_search_table, top_sites_table, top_urls_table, top_users_table.
GRPCOLOR
Referenced by top_agents_table, top_refs_table, top_search_table, top_sites_table, top_urls_table, top_users_table.
void write_html_head(char *, FILE *)
References BLACK, BLUE, cur_time, editlvl, hname, html_body, html_head, html_post, html_pre, LTGREY, msg_hhdr_gt, msg_hhdr_sp, msg_title, nlist::next, RED, nlist::string, version.
Referenced by all_agents_page, all_refs_page, all_search_page, all_sites_page, all_urls_page, all_users_page, write_month_html.
void write_html_tail(FILE *)
References editlvl, html_end, html_tail, moddate, nlist::next, nlist::string, version.
Referenced by all_agents_page, all_refs_page, all_search_page, all_sites_page, all_urls_page, all_users_page, write_month_html.
void month_links()
References daily_graph, daily_stats, hourly_graph, hourly_stats, msg_hlnk_a, msg_hlnk_c, msg_hlnk_ds, msg_hlnk_en, msg_hlnk_ex, msg_hlnk_hs, msg_hlnk_i, msg_hlnk_r, msg_hlnk_s, msg_hlnk_sr, msg_hlnk_u, ntop_agents, ntop_ctrys, ntop_entry, ntop_exit, ntop_notfound, ntop_refs, ntop_search, ntop_sites, ntop_sitesK, ntop_urls, ntop_urlsK, ntop_users, out_fp, response, t_agent, t_ref, t_user.
Referenced by write_month_html.
void month_total_table()
References f_day, l_day, tm_file, tm_hit, tm_page, tm_visit, tm_xfer.
Referenced by write_month_html.
void month_error_table()
References response_url::count, responsetmp_url::count, resp_counter, respnotfound, respnotfoundtmp, response_url::respurl, responsetmp_url::respurl.
Referenced by write_month_html.
void daily_total_table()
References cur_month, cur_year, CYAN, DKGREEN, GREY, hist_lday, l_month, LTBLUE, msg_dtot_ds, msg_h_day, msg_h_files, msg_h_hits, msg_h_pages, msg_h_sites, msg_h_visits, msg_h_xfer, ORANGE, out_fp, PCENT, RED, t_file, t_hit, t_page, t_site, t_visit, t_xfer, tm_file, tm_hit, tm_page, tm_site, tm_visit, tm_xfer, YELLOW.
Referenced by write_month_html.
void hourly_total_table()
References cur_month, cur_year, CYAN, DKGREEN, f_day, GREY, l_day, l_month, LTBLUE, msg_h_avg, msg_h_files, msg_h_hits, msg_h_hour, msg_h_pages, msg_h_total, msg_h_xfer, msg_htot_hs, out_fp, PCENT, RED, t_file, t_hit, t_page, t_xfer, th_file, th_hit, th_page, th_xfer.
Referenced by write_month_html.
void top_sites_table(int)
References a_ctr, all_sites, all_sites_page, hnode::count, cur_month, cur_year, CYAN, DKGREEN, hnode::files, hnode::flag, GREY, GRPCOLOR, h_array, hlite_groups, html_ext, LTBLUE, msg_h_by, msg_h_files, msg_h_hits, msg_h_hname, msg_h_visits, msg_h_xfer, msg_top_of, msg_top_s, msg_top_top, msg_v_sites, ntop_sites, ntop_sitesK, OBJ_GRP, OBJ_HIDE, OBJ_REG, out_fp, qs_site_cmph, RED, shade_groups, hnode::string, t_file, t_hit, t_site, t_visit, t_xfer, hnode::visit, hnode::xfer, YELLOW.
Referenced by write_month_html.
void top_urls_table(int)
References a_ctr, all_urls, all_urls_page, unode::count, cur_month, cur_year, CYAN, DKGREEN, unode::flag, GREY, GRPCOLOR, hlite_groups, hname, html_ext, LOG_FTP, log_type, msg_h_by, msg_h_hits, msg_h_url, msg_h_xfer, msg_top_of, msg_top_top, msg_top_u, msg_v_urls, ntop_urls, ntop_urlsK, OBJ_GRP, OBJ_HIDE, OBJ_REG, out_fp, qs_url_cmph, RED, shade_groups, unode::string, t_hit, t_url, t_xfer, u_array, use_https, unode::xfer.
Referenced by write_month_html.
void top_entry_table(int)
References a_ctr, unode::count, CYAN, DKGREEN, unode::entry, unode::exit, unode::flag, GREY, hname, msg_h_hits, msg_h_url, msg_h_visits, msg_top_en, msg_top_ex, msg_top_of, msg_top_top, ntop_entry, ntop_exit, OBJ_HIDE, OBJ_REG, out_fp, unode::string, t_hit, u_array, use_https, YELLOW.
Referenced by write_month_html.
void top_refs_table()
References a_ctr, all_refs, all_refs_page, rnode::count, cur_month, cur_year, CYAN, DKGREEN, rnode::flag, GREY, GRPCOLOR, hlite_groups, html_ext, msg_h_hits, msg_h_ref, msg_top_of, msg_top_r, msg_top_top, msg_v_refs, ntop_refs, OBJ_GRP, OBJ_HIDE, OBJ_REG, out_fp, r_array, shade_groups, rnode::string, t_hit, t_ref.
Referenced by write_month_html.
void top_agents_table()
References a_array, a_ctr, all_agents, all_agents_page, anode::count, cur_month, cur_year, CYAN, DKGREEN, anode::flag, GREY, GRPCOLOR, hlite_groups, html_ext, msg_h_agent, msg_h_hits, msg_top_a, msg_top_of, msg_top_top, msg_v_agents, ntop_agents, OBJ_GRP, OBJ_HIDE, OBJ_REG, out_fp, shade_groups, anode::string, t_agent, t_hit.
Referenced by write_month_html.
void top_ctry_table()
References hnode::count, responsetmp_url::count, ctry, ctry_graph, hnode::files, country_code::files, hnode::flag, MAXHASH, OBJ_GRP, sm_htab, hnode::string, hnode::xfer, country_code::xfer.
Referenced by write_month_html.
void top_search_table()
References a_ctr, all_search, all_search_page, snode::count, cur_month, cur_year, CYAN, DKGREEN, GREY, GRPCOLOR, html_ext, msg_h_hits, msg_h_search, msg_top_of, msg_top_sr, msg_top_top, msg_v_search, ntop_search, out_fp, s_array, snode::string, t_ref.
Referenced by write_month_html.
void top_users_table()
References a_ctr, all_users, all_users_page, inode::count, cur_month, cur_year, CYAN, DKGREEN, inode::files, inode::flag, GREY, GRPCOLOR, hlite_groups, html_ext, i_array, LTBLUE, msg_h_files, msg_h_hits, msg_h_uname, msg_h_visits, msg_h_xfer, msg_top_i, msg_top_of, msg_top_top, msg_v_users, ntop_users, OBJ_GRP, OBJ_HIDE, OBJ_REG, out_fp, RED, shade_groups, inode::string, t_file, t_hit, t_user, t_visit, t_xfer, inode::visit, inode::xfer, YELLOW.
Referenced by write_month_html.
u_long load_url_array(UNODEPTR *)
References MAXHASH, unode::next, um_htab.
Referenced by write_month_html.
u_long load_site_array(HNODEPTR *)
References MAXHASH, hnode::next, sm_htab.
Referenced by write_month_html.
u_long load_ref_array(RNODEPTR *)
References MAXHASH, rnode::next, rm_htab.
Referenced by write_month_html.
u_long load_agent_array(ANODEPTR *)
References am_htab, MAXHASH, anode::next.
Referenced by write_month_html.
u_long load_srch_array(SNODEPTR *)
References MAXHASH, snode::next, sr_htab.
Referenced by write_month_html.
u_long load_ident_array(INODEPTR *)
References im_htab, MAXHASH, inode::next.
Referenced by write_month_html.
int qs_url_cmph(const void *, const void *)
Referenced by top_urls_table, write_month_html.
int qs_url_cmpk(const void *, const void *)
Referenced by write_month_html.
int qs_url_cmpn(const void *, const void *)
Referenced by write_month_html.
int qs_url_cmpx(const void *, const void *)
Referenced by write_month_html.
int qs_site_cmph(const void *, const void *)
Referenced by top_sites_table, write_month_html.
int qs_site_cmpk(const void *, const void *)
Referenced by write_month_html.
int qs_ref_cmph(const void *, const void *)
Referenced by write_month_html.
int qs_agnt_cmph(const void *, const void *)
Referenced by write_month_html.
int qs_srch_cmph(const void *, const void *)
Referenced by write_month_html.
int qs_ident_cmph(const void *, const void *)
Referenced by write_month_html.
int qs_ident_cmpk(const void *, const void *)
int all_sites_page(u_long, u_long)
References buffer, hnode::count, cur_month, cur_year, hnode::files, hnode::flag, h_array, hide_sites, html_ext, l_month, msg_h_files, msg_h_hits, msg_h_hname, msg_h_sites, msg_h_visits, msg_h_xfer, OBJ_GRP, OBJ_REG, open_out_file, out_fp, hnode::string, t_file, t_hit, t_visit, t_xfer, hnode::visit, write_html_head, write_html_tail, hnode::xfer.
Referenced by top_sites_table.
int all_urls_page(u_long, u_long)
References buffer, unode::count, cur_month, cur_year, unode::flag, html_ext, l_month, msg_h_hits, msg_h_url, msg_h_xfer, OBJ_GRP, OBJ_REG, open_out_file, out_fp, unode::string, t_hit, t_xfer, u_array, write_html_head, write_html_tail, unode::xfer.
Referenced by top_urls_table.
int all_refs_page(u_long, u_long)
References buffer, rnode::count, cur_month, cur_year, rnode::flag, html_ext, l_month, msg_h_hits, msg_h_ref, OBJ_GRP, OBJ_REG, open_out_file, out_fp, r_array, rnode::string, t_hit, write_html_head, write_html_tail.
Referenced by top_refs_table.
int all_agents_page(u_long, u_long)
References a_array, buffer, anode::count, cur_month, cur_year, anode::flag, html_ext, l_month, msg_h_agent, msg_h_hits, OBJ_GRP, OBJ_REG, open_out_file, out_fp, anode::string, t_hit, write_html_head, write_html_tail.
Referenced by top_agents_table.
int all_search_page(u_long, u_long)
References buffer, snode::count, cur_month, cur_year, html_ext, l_month, msg_h_hits, msg_h_search, open_out_file, out_fp, s_array, snode::string, write_html_head, write_html_tail.
Referenced by top_search_table.
int all_users_page(u_long, u_long)
References buffer, inode::count, cur_month, cur_year, inode::files, inode::flag, html_ext, i_array, l_month, msg_h_files, msg_h_hits, msg_h_uname, msg_h_visits, msg_h_xfer, OBJ_GRP, OBJ_REG, open_out_file, out_fp, inode::string, t_file, t_hit, t_visit, t_xfer, inode::visit, write_html_head, write_html_tail, inode::xfer.
Referenced by top_users_table.
void dump_all_sites()
References a_ctr, hnode::count, cur_month, cur_year, dump_ext, dump_header, dump_path, hnode::files, hnode::flag, h_array, msg_h_files, msg_h_hits, msg_h_hname, msg_h_visits, msg_h_xfer, OBJ_GRP, open_out_file, out_fp, hnode::string, hnode::visit, hnode::xfer.
Referenced by write_month_html.
void dump_all_urls()
References a_ctr, unode::count, cur_month, cur_year, dump_ext, dump_header, dump_path, unode::flag, msg_h_hits, msg_h_url, msg_h_xfer, OBJ_GRP, open_out_file, out_fp, unode::string, u_array, unode::xfer.
Referenced by write_month_html.
void dump_all_refs()
References a_ctr, rnode::count, cur_month, cur_year, dump_ext, dump_header, dump_path, rnode::flag, msg_h_hits, msg_h_ref, OBJ_GRP, open_out_file, out_fp, r_array, rnode::string.
Referenced by write_month_html.
void dump_all_agents()
References a_array, a_ctr, anode::count, cur_month, cur_year, dump_ext, dump_header, dump_path, anode::flag, msg_h_agent, msg_h_hits, OBJ_GRP, open_out_file, out_fp, anode::string.
Referenced by write_month_html.
void dump_all_users()
References a_ctr, inode::count, cur_month, cur_year, dump_ext, dump_header, dump_path, inode::files, inode::flag, i_array, msg_h_files, msg_h_hits, msg_h_uname, msg_h_visits, msg_h_xfer, OBJ_GRP, open_out_file, out_fp, inode::string, inode::visit, inode::xfer.
Referenced by write_month_html.
void dump_all_search()
References a_ctr, snode::count, cur_month, cur_year, dump_ext, dump_header, dump_path, msg_h_hits, msg_h_search, open_out_file, out_fp, s_array, snode::string.
Referenced by write_month_html.
int write_month_html()
References a_array, a_ctr, buffer, BUFSIZE, cur_month, cur_year, daily_graph, daily_stats, daily_total_table, day_graph3, dump_agents, dump_all_agents, dump_all_refs, dump_all_search, dump_all_sites, dump_all_urls, dump_all_users, dump_refs, dump_search, dump_sites, dump_urls, dump_users, f_day, h_array, hist_fday, hist_files, hist_hit, hist_lday, hist_month, hist_page, hist_site, hist_visit, hist_xfer, hist_year, hourly_graph, hourly_stats, hourly_total_table, html_ext, i_array, l_day, l_month, load_agent_array, load_ident_array, load_ref_array, load_site_array, load_srch_array, load_url_array, month_error_table, month_graph6, month_links, month_total_table, msg_gen_rpt, msg_hmth_du, msg_hmth_hu, msg_nomem_ta, msg_nomem_ti, msg_nomem_tr, msg_nomem_ts, msg_nomem_tsr, msg_nomem_tu, ntop_agents, ntop_ctrys, ntop_entry, ntop_exit, ntop_notfound, ntop_refs, ntop_search, ntop_sites, ntop_sitesK, ntop_urls, ntop_urlsK, ntop_users, open_out_file, out_fp, qs_agnt_cmph, qs_ident_cmph, qs_ref_cmph, qs_site_cmph, qs_site_cmpk, qs_srch_cmph, qs_url_cmph, qs_url_cmpk, qs_url_cmpn, qs_url_cmpx, r_array, response, s_array, t_file, t_hit, t_page, t_site, t_visit, t_xfer, th_file, th_hit, th_page, tm_file, tm_hit, tm_page, tm_site, tm_visit, tm_xfer, top_agents_table, top_ctry_table, top_entry_table, top_refs_table, top_search_table, top_sites_table, top_urls_table, top_users_table, u_array, verbose, write_html_head, write_html_tail.
int write_main_index()
References buffer, BUFSIZE, hist_month, hist_year, hname, msg_gen_sum, msg_main_us, verbose.
FILE* open_out_file(char *filename)
References msg_no_open, out_fp, verbose.
Referenced by all_agents_page, all_refs_page, all_search_page, all_sites_page, all_urls_page, all_users_page, dump_all_agents, dump_all_refs, dump_all_search, dump_all_sites, dump_all_urls, dump_all_users, write_month_html.
UNODEPTR* u_array
Referenced by all_urls_page, dump_all_urls, top_entry_table, top_urls_table, write_month_html.
HNODEPTR* h_array
Referenced by all_sites_page, dump_all_sites, top_sites_table, write_month_html.
RNODEPTR* r_array
Referenced by all_refs_page, dump_all_refs, top_refs_table, write_month_html.
ANODEPTR* a_array
Referenced by all_agents_page, dump_all_agents, top_agents_table, write_month_html.
SNODEPTR* s_array
Referenced by all_search_page, dump_all_search, top_search_table, write_month_html.
INODEPTR* i_array
Referenced by all_users_page, dump_all_users, top_users_table, write_month_html.
u_long a_ctr
Referenced by dump_all_agents, dump_all_refs, dump_all_search, dump_all_sites, dump_all_urls, dump_all_users, top_agents_table, top_entry_table, top_refs_table, top_search_table, top_sites_table, top_urls_table, top_users_table, write_month_html.
FILE* out_fp
Referenced by all_agents_page, all_refs_page, all_search_page, all_sites_page, all_urls_page, all_users_page, daily_total_table, dump_all_agents, dump_all_refs, dump_all_search, dump_all_sites, dump_all_urls, dump_all_users, hourly_total_table, month_links, open_out_file, top_agents_table, top_entry_table, top_refs_table, top_search_table, top_sites_table, top_urls_table, top_users_table, write_month_html.