output.h
int write_main_index()
References buffer, BUFSIZE, hist_month, hist_year, hname, msg_gen_sum, msg_main_us, verbose.
int write_month_html()
References a_array, a_ctr, buffer, BUFSIZE, cur_month, cur_year, daily_graph, daily_stats, daily_total_table, day_graph3, dump_agents, dump_all_agents, dump_all_refs, dump_all_search, dump_all_sites, dump_all_urls, dump_all_users, dump_refs, dump_search, dump_sites, dump_urls, dump_users, f_day, h_array, hist_fday, hist_files, hist_hit, hist_lday, hist_month, hist_page, hist_site, hist_visit, hist_xfer, hist_year, hourly_graph, hourly_stats, hourly_total_table, html_ext, i_array, l_day, l_month, load_agent_array, load_ident_array, load_ref_array, load_site_array, load_srch_array, load_url_array, month_error_table, month_graph6, month_links, month_total_table, msg_gen_rpt, msg_hmth_du, msg_hmth_hu, msg_nomem_ta, msg_nomem_ti, msg_nomem_tr, msg_nomem_ts, msg_nomem_tsr, msg_nomem_tu, ntop_agents, ntop_ctrys, ntop_entry, ntop_exit, ntop_notfound, ntop_refs, ntop_search, ntop_sites, ntop_sitesK, ntop_urls, ntop_urlsK, ntop_users, open_out_file, out_fp, qs_agnt_cmph, qs_ident_cmph, qs_ref_cmph, qs_site_cmph, qs_site_cmpk, qs_srch_cmph, qs_url_cmph, qs_url_cmpk, qs_url_cmpn, qs_url_cmpx, r_array, response, s_array, t_file, t_hit, t_page, t_site, t_visit, t_xfer, th_file, th_hit, th_page, tm_file, tm_hit, tm_page, tm_site, tm_visit, tm_xfer, top_agents_table, top_ctry_table, top_entry_table, top_refs_table, top_search_table, top_sites_table, top_urls_table, top_users_table, u_array, verbose, write_html_head, write_html_tail.
FILE* open_out_file(char *)
References msg_no_open, out_fp, verbose.
Referenced by all_agents_page, all_refs_page, all_search_page, all_sites_page, all_urls_page, all_users_page, dump_all_agents, dump_all_refs, dump_all_search, dump_all_sites, dump_all_urls, dump_all_users, write_month_html.