parser.c
CLK_TCK
void fmt_logrec(char *)
Referenced by parse_record_ftp, parse_record_squid, parse_record_web.
int parse_record_web(char *)
References log_struct::agent, log_struct::datetime, debug_mode, fmt_logrec, log_struct::hostname, log_struct::ident, log_rec, MAXAGENT, MAXHOST, MAXIDENT, MAXREF, MAXURL, msg_big_date, msg_big_host, msg_big_ref, msg_big_req, msg_big_user, log_struct::refer, log_struct::resp_code, log_struct::url, verbose, log_struct::xfer_size.
Referenced by parse_record.
int parse_record_ftp(char *)
References log_struct::datetime, fmt_logrec, log_struct::hostname, log_struct::ident, log_rec, MAXHOST, MAXURL, log_struct::resp_code, log_struct::url, log_struct::xfer_size.
Referenced by parse_record.
int parse_record_squid(char *)
References log_struct::datetime, debug_mode, fmt_logrec, log_struct::hostname, log_struct::ident, log_rec, MAXHOST, MAXIDENT, MAXURL, msg_big_host, msg_big_req, log_struct::resp_code, log_struct::url, verbose, log_struct::xfer_size.
Referenced by parse_record.
int parse_record(char *buffer)
References LOG_CLF, LOG_FTP, log_rec, LOG_SQUID, log_type, parse_record_ftp, parse_record_squid, parse_record_web.